# Generated by Django 4.2.30 on 2026-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unifica_municipios_92'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('regiao', models.CharField(choices=[('BAIXADA FLUMINENSE', 'BAIXADA FLUMINENSE'), ('BAIXADA LITORÂNEA', 'BAIXADA LITORÂNEA'), ('CAPITAL', 'CAPITAL'), ('COSTA VERDE', 'COSTA VERDE'), ('METROPOLITANA', 'METROPOLITANA'), ('NORTE', 'NORTE'), ('NOROESTE', 'NOROESTE'), ('SERRANA I', 'SERRANA I'), ('SERRANA II', 'SERRANA II'), ('SUL I', 'SUL I'), ('SUL II', 'SUL II')], max_length=30)),
                ('temperatura_maxima', models.SmallIntegerField()),
                ('temperatura_minima', models.SmallIntegerField()),
                ('umidade_maxima', models.PositiveSmallIntegerField()),
                ('umidade_minima', models.PositiveSmallIntegerField()),
                ('vento_velocidade', models.CharField(choices=[('Fraco', 'Fraco'), ('Fraco/Moderado', 'Fraco/Moderado'), ('Moderado', 'Moderado'), ('Moderado/Forte', 'Moderado/Forte'), ('Forte', 'Forte')], default='Fraco', max_length=20)),
                ('vento_direcao', models.CharField(blank=True, max_length=20)),
                ('nascer_sol', models.CharField(blank=True, max_length=5)),
                ('por_sol', models.CharField(blank=True, max_length=5)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('icone', models.CharField(blank=True, choices=[('ceuClaro', 'Céu claro'), ('ceuPoucasNuvens', 'Poucas nuvens'), ('ceuParcialmenteNublado', 'Parcialmente nublado'), ('ceuParcialmenteNubladoChuva', 'Parcialmente nublado com chuva'), ('ceuParcialmenteNubladoChuvaRaios', 'Parcialmente nublado com chuva e raios'), ('ceuNublado', 'Nublado'), ('ceuNubladoChuva', 'Nublado com chuva'), ('ceuNubladoChuvaRaios', 'Nublado com chuva e raios'), ('ceuEncoberto', 'Encoberto'), ('ceuEncobertoChuva', 'Encoberto com chuva'), ('ceuEncobertoChuvaRaio', 'Encoberto com chuva e raio')], max_length=40)),
                ('origem', models.CharField(default='painel', help_text="'painel' ou 'legado' (importado).", max_length=10)),
                ('legado_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('criado_por', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=150)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data', 'regiao'],
            },
        ),
        migrations.AddConstraint(
            model_name='previsao',
            constraint=models.UniqueConstraint(fields=('data', 'regiao'), name='unique_previsao_data_regiao'),
        ),
    ]
