# Generated by Django 4.2.30 on 2026-09-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_previsao'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ana_codigo_flu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código ANA (flu)'),
        ),
        migrations.AddField(
            model_name='station',
            name='ana_codigo_plu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código ANA (plu)'),
        ),
        migrations.AddField(
            model_name='station',
            name='bacia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='station',
            name='regiao_hidrografica',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='station',
            name='rio_monitorado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='CotaHidrologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencao_cm', models.FloatField(blank=True, null=True)),
                ('alerta_cm', models.FloatField(blank=True, null=True)),
                ('inundacao_cm', models.FloatField(blank=True, null=True, verbose_name='Transbordo (inundação) cm')),
                ('extrema_cm', models.FloatField(blank=True, help_text='Vazio = 20% acima da cota de inundação (calculado).', null=True)),
                ('rio', models.CharField(blank=True, max_length=120)),
                ('codigo_referencia', models.CharField(blank=True, help_text='CODIGO na planilha INEA/CPRM.', max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=40)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cota', to='core.station')),
            ],
            options={
                'verbose_name': 'cota hidrológica',
                'verbose_name_plural': 'cotas hidrológicas',
            },
        ),
    ]
