# Generated by Django 4.2.30 on 2026-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carrega_hidro_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='reading_type',
            field=models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('vento_rajada_ms', 'Rajada de vento (m/s)'), ('vento_dir_graus', 'Direção do vento (graus)'), ('mare_m', 'Maré (m)'), ('temperatura_max_c', 'Temperatura máxima (°C)'), ('temperatura_min_c', 'Temperatura mínima (°C)'), ('umidade_max_pct', 'Umidade máxima (%)'), ('umidade_min_pct', 'Umidade mínima (%)'), ('pressao_hpa', 'Pressão na estação (hPa)'), ('pressao_nm_hpa', 'Pressão ao nível do mar (hPa)'), ('ponto_orvalho_c', 'Ponto de orvalho (°C)'), ('radiacao_wm2', 'Radiação solar (W/m²)'), ('uv_indice', 'Índice UV'), ('sensacao_termica_c', 'Sensação térmica (°C)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_type',
            field=models.CharField(choices=[('chuva_mm', 'Chuva acumulada (mm)'), ('nivel_m', 'Nível do rio (m)'), ('temperatura_c', 'Temperatura (°C)'), ('umidade_pct', 'Umidade relativa (%)'), ('vento_ms', 'Vento (m/s)'), ('vento_rajada_ms', 'Rajada de vento (m/s)'), ('vento_dir_graus', 'Direção do vento (graus)'), ('mare_m', 'Maré (m)'), ('temperatura_max_c', 'Temperatura máxima (°C)'), ('temperatura_min_c', 'Temperatura mínima (°C)'), ('umidade_max_pct', 'Umidade máxima (%)'), ('umidade_min_pct', 'Umidade mínima (%)'), ('pressao_hpa', 'Pressão na estação (hPa)'), ('pressao_nm_hpa', 'Pressão ao nível do mar (hPa)'), ('ponto_orvalho_c', 'Ponto de orvalho (°C)'), ('radiacao_wm2', 'Radiação solar (W/m²)'), ('uv_indice', 'Índice UV'), ('sensacao_termica_c', 'Sensação térmica (°C)')], max_length=20),
        ),
    ]
