# Generated by Django 4.2.30 on 2026-09-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_radiacao_plugfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SireneAcaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('categoria', models.CharField(choices=[('normal', 'Normal / retorno à normalidade'), ('aviso', 'Aviso de chuva'), ('teste', 'Teste de manutenção'), ('mobilizacao', 'Mobilização'), ('outro', 'Outro / a confirmar')], default='outro', max_length=15)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de acionamento de sirene',
                'verbose_name_plural': 'tipos de acionamento de sirene',
                'ordering': ['codigo'],
            },
        ),
    ]
