# Generated by Django 4.2.30 on 2026-09-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sirene_tipos_e_niteroi_m15'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatilhoPluviometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=120, unique=True)),
                ('gatilho_i_1h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho I — chuva 1h (mm)')),
                ('gatilho_ii_1h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho II — chuva 1h (mm)')),
                ('gatilho_ii_24h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho II — chuva 24h (mm)')),
                ('gatilho_iii_1h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho III — chuva 1h (mm)')),
                ('gatilho_iii_96h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho III — chuva 96h (mm)')),
                ('gatilho_iv_1h_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho IV — chuva 1h (mm)')),
                ('gatilho_iv_30d_mm', models.FloatField(blank=True, null=True, verbose_name='Gatilho IV — chuva 30 dias (mm)')),
            ],
            options={
                'verbose_name': 'gatilho pluviométrico (por município)',
                'verbose_name_plural': 'gatilhos pluviométricos (por município)',
                'ordering': ['municipio'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='risco_sirene',
            field=models.CharField(blank=True, choices=[('geo', 'Geológico'), ('hidro', 'Hidrológico'), ('geo_hidro', 'Geológico + Hidrológico')], help_text='Não vem de nenhuma fonte automática — classificação manual por sirene.', max_length=10, verbose_name='Tipo de risco (sirene)'),
        ),
        migrations.AddField(
            model_name='station',
            name='sirene_ref',
            field=models.ForeignKey(blank=True, help_text='Estação com pluviômetro usada pra calcular os gatilhos desta sirene quando ela não tem pluviômetro próprio. Pré-preenchida automaticamente com a estação pluviométrica mais próxima dentro de 2km (ver management command populate_sirene_ref) — editável aqui manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sirenes_referenciadas', to='core.station', verbose_name='Estação de referência (REF)'),
        ),
        migrations.AddField(
            model_name='station',
            name='tipo_sirene',
            field=models.CharField(blank=True, choices=[('EAA', 'Simples (EAA)'), ('EAA+P', 'Com pluviômetro (EAA+P)'), ('EAA+H', 'Com estação hidrológica (EAA+H)'), ('EAA+M', 'Com estação meteorológica (EAA+M)')], help_text='EAA/EAA+P são derivados automaticamente (tem ou não pluviômetro); EAA+H/EAA+M são atribuídos manualmente quando essas sirenes existirem.', max_length=10, verbose_name='Tipo de sirene'),
        ),
    ]
