# Generated by Django 4.2.30 on 2026-10-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_seed_gatilhos_e_tipo_sirene"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoMauTempo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_externo",
                    models.CharField(
                        help_text="Ex: '716/2026' — número do boletim na fonte.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[("CHARLIE", "Área Charlie"), ("DELTA", "Área Delta")],
                        max_length=10,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Texto do tipo de aviso como vem da fonte (ex: 'VENTO FORTE', 'MAR GROSSO').",
                        max_length=80,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Texto completo do aviso (área geográfica, intensidade, etc)."
                    ),
                ),
                ("emitido_em", models.DateTimeField(blank=True, null=True)),
                ("valido_ate", models.DateTimeField(blank=True, null=True)),
                (
                    "fonte",
                    models.CharField(
                        blank=True,
                        default="Marinha do Brasil - SMM/CHM",
                        max_length=120,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "aviso de mau tempo (Marinha)",
                "verbose_name_plural": "avisos de mau tempo (Marinha)",
                "ordering": ["-emitido_em", "area"],
            },
        ),
    ]
