# Generated by Django 4.2.30 on 2026-10-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_avisomautempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.CharField(choices=[('suspeito', 'Suspeito'), ('invalido', 'Inválido')], max_length=10)),
                ('motivo', models.CharField(max_length=120)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualidade', to='core.reading')),
            ],
            options={
                'verbose_name': 'qualificação de leitura',
                'verbose_name_plural': 'qualificações de leitura',
            },
        ),
        migrations.CreateModel(
            name='AcumuladoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janela_h', models.PositiveSmallIntegerField(help_text='Janela do acumulado em horas (1, 24 ou 96).')),
                ('valor_mm', models.FloatField()),
                ('referencia', models.DateTimeField(help_text='Horário (UTC) da última leitura da estação a que o acumulado se refere.')),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acumulados_oficiais', to='core.station')),
            ],
            options={
                'verbose_name': 'acumulado oficial da fonte',
                'verbose_name_plural': 'acumulados oficiais da fonte',
                'ordering': ['-referencia'],
                'indexes': [models.Index(fields=['station', 'janela_h', '-referencia'], name='core_acumul_station_97b369_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='acumuladooficial',
            constraint=models.UniqueConstraint(fields=('station', 'janela_h', 'referencia'), name='unique_acumulado_oficial'),
        ),
    ]
